export const ITEM_PHOTOS: { [key: string]: string[] } = {
  BITS: [
    `${process.env.AMAZON_S3_URL}/BI-Tshirt/BI_NATURAL_BACK.jpg`,
    `${process.env.AMAZON_S3_URL}/BI-Tshirt/BI_NATURAL2.jpg`,
    `${process.env.AMAZON_S3_URL}/BI-Tshirt/BI_GRAY.jpg`,
    `${process.env.AMAZON_S3_URL}/BI-Tshirt/BI_GRAY_BACK.jpg`,
    `${process.env.AMAZON_S3_URL}/BI-Tshirt/BI_GROUP.jpg`,
  ],
  KPPN: [
    `${process.env.AMAZON_S3_URL}/KP-Joggers/BLACK_JOGGER_FULL_BODY.jpg`,

    `${process.env.AMAZON_S3_URL}/KP-Joggers/FULL_BODY_BLACK_JOGGER.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-Joggers/BLACK_JOGGER_FRONT.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-Joggers/BLACK_JOGGER_POSE3.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-Joggers/BLACK_JOGGER_BACK.jpg`,
  ],
  KPSR: [
    `${process.env.AMAZON_S3_URL}/KP-Shorts/WHITE_SHORT_BACK.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-Shorts/WHITE_OUTFIT_SHORTS.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-Shorts/BLACK_SHORTS_SIDE.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-Shorts/BLACK_SHORTS_BACK.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-Shorts/BLACK_WHITE_SHORTS.jpg`,
  ],
  HMTS: [
    `${process.env.AMAZON_S3_URL}/HM-Tshirt/HM_JANE_FRONT.jpg`,
    `${process.env.AMAZON_S3_URL}/HM-Tshirt/HM_JANE_BACK.jpg`,
    `${process.env.AMAZON_S3_URL}/HM-Tshirt/HM_GRAY_FRONT.jpg`,
    `${process.env.AMAZON_S3_URL}/HM-Tshirt/HM_GRAY_BACK.jpg`,
    `${process.env.AMAZON_S3_URL}/HM-Tshirt/HM_GROUP_PHOTO.jpg`,
  ],
  YNMTS: [
    `${process.env.AMAZON_S3_URL}/INYM-tshirt/INYM_BACK_BLACK2.jpg`,
    `${process.env.AMAZON_S3_URL}/INYM-tshirt/INYM_COUPLE_FRONT.jpg`,
    `${process.env.AMAZON_S3_URL}/INYM-tshirt/PINK_FRONT2_INYM.jpg`,
    `${process.env.AMAZON_S3_URL}/INYM-tshirt/INYM_COUPLE2_BACK.jpg`,
    `${process.env.AMAZON_S3_URL}/INYM-tshirt/INYM_GROUP.jpg`,
  ],
  ICTS: [
    `${process.env.AMAZON_S3_URL}/Iconic-TS/ICONIC_BACK.jpg`,
    `${process.env.AMAZON_S3_URL}/Iconic-TS/ICONIC_FRONT_POSE.jpg`,
    `${process.env.AMAZON_S3_URL}/Iconic-TS/ICONIC_MAN_STANDING.jpg`,
    `${process.env.AMAZON_S3_URL}/Iconic-TS/ICONIC_MAN.jpg`,
  ],
  AQTS: [
    `${process.env.AMAZON_S3_URL}/AQ-Tshirts/AQ_PINK_FRONT.jpg`,
    `${process.env.AMAZON_S3_URL}/AQ-Tshirts/AQ_PINK_BACK.jpg`,
    `${process.env.AMAZON_S3_URL}/AQ-Tshirts/AQ_BLACK_FRONT.jpg`,
    `${process.env.AMAZON_S3_URL}/AQ-Tshirts/AQ_BLACK_POSE.jpg`,
    `${process.env.AMAZON_S3_URL}/AQ-Tshirts/AQ_BACK_BLACK.jpg`,
  ],
  AQCPCK: [
    `${process.env.AMAZON_S3_URL}/AQ-Crewneck/AQ_CREWNECK_FRONT.jpg`,
    `${process.env.AMAZON_S3_URL}/AQ-Crewneck/AQ_CREWNECK_BACK.jpg`,
    `${process.env.AMAZON_S3_URL}/AQ-Crewneck/AQ_CK_FRONT_POSE.jpg`,
    `${process.env.AMAZON_S3_URL}/AQ-Crewneck/AQ_POSE_CK.jpg`,
    `${process.env.AMAZON_S3_URL}/AQ-Crewneck/AQ_CK_GIRLS.jpg`,
  ],
  KPNCK: [
    `${process.env.AMAZON_S3_URL}/KP-CK-NEON/KP_NEON_BOY.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-CK-NEON/KP_NEON_BACK.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-CK-NEON/FRONT_NEON.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-CK-NEON/KP_CK_NEON_POSE.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-CK-NEON/KP_NEON_FIRLS.jpg`,
  ],
  KPCK: [
    `${process.env.AMAZON_S3_URL}/KP-Crewneck/CREWNECK_NUDE_PSOE.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-Crewneck/KP_CREWNECK_NATURAL_CLSEUP.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-Crewneck/CREWNECK_NUDE_BACK.jpg`,

    `${process.env.AMAZON_S3_URL}/KP-Crewneck/CREWNECK_GRAY_FRONT.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-Crewneck/CREWNECK_GRAY_BACK2.jpg`,
  ],
  KPHD: [
    `${process.env.AMAZON_S3_URL}/KP-Hoodies/KP_BLACK_HOODIE_BACK.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-Hoodies/KP_HOODIE_DUO.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-Hoodies/WHITE_HOODIE_FRONT2.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-Hoodies/WHITE_HOODIE_POSE.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-Hoodies/KP_HOODIE_GROUP.jpg`,
  ],
  KPTS: [
    `${process.env.AMAZON_S3_URL}/KP-Tshirts/KP_TS_FRONT.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-Tshirts/KP_FRONT_TS.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-Tshirts/KP_TS_BACK.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-Tshirts/KP_TS_POSE.jpg`,
    `${process.env.AMAZON_S3_URL}/KP-Tshirts/KP_TS_POSE2.jpg`,
  ],
};
