import type { Metadata } from "next";
import { ShoppingCartProvider } from "@/context/shopping-cart";
import TopNav from "@/components/TopNav";
import Link from "next/link";

import { Inter, Bebas_Neue, DM_Sans } from "next/font/google";
import "./globals.css";
import { AlterNav } from "@/components/AlterNav";

export const inter = Inter({ subsets: ["latin"] });
export const bebas_neue = Bebas_Neue({ weight: ["400"], subsets: ["latin"] });
export const dm_sans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kinda Problematic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={dm_sans.className}>
        <ShoppingCartProvider>
          <AlterNav />
          <div>{children}</div>
        </ShoppingCartProvider>
      </body>
    </html>
  );
}
