import type { Metadata } from "next";
import { ShoppingCartProvider } from "@/context/shopping-cart";
import TopNav from "@/components/TopNav";
import Link from "next/link";

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kinda Problematic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopNav />
        <ShoppingCartProvider><div className="p-14">{children}</div></ShoppingCartProvider>
      </body>
    </html>
  );
}
